# This code adds all system apps to Magiskhide list. But I don't know how to see procs with .sh If you want to develop it, send a pull request.
# May be incompatible with other modules!
# Move to /data/adb/SystemAppAdd.sh and rum.

# Telegram: t.me/cleverestech

su -c rm -f /data/adb/AllAppsTarget.sh

packages=(
  android.aosp.overlay\|android.aosp.overlay
  android.aosp.overlay.telephony\|android.aosp.overlay.telephony
  android.miui.home.launcher.res\|android.miui.home.launcher.res
  android.miui.overlay\|android.miui.overlay
  android.miui.overlay.telephony\|android.miui.overlay.telephony
  android.overlay.common\|android.overlay.common
  android.overlay.target\|android.overlay.target
  android.qvaoverlay.common\|android.qvaoverlay.common
  com.a101kapida.android\|com.a101kapida.android
  com.a101kapida.android\|com.a101kapida.android:container
  com.a101kapida.android\|com.a101kapida.android:playcore_missing_splits_activity
  com.ahlatci.ahlpay\|com.ahlatci.ahlpay
  com.akbank.android.apps.akbank_direkt\|com.akbank.android.apps.akbank_direkt
  com.akbank.android.apps.akbank_direkt\|com.akbank.android.apps.akbank_direkt:error_activity
  com.akbank.android.apps.akbank_direkt\|com.akbank.android.apps.akbank_direkt:playcore_missing_splits_activity
  com.akbank.android.apps.akbank_direkt\|com.akbank.android.apps.akbank_direkt:pushservice
  com.akbank.android.apps.akbank_direkt\|com.akbank.android.apps.akbank_direkt:remote
  com.akbank.android.apps.axess\|com.akbank.android.apps.axess
  com.akbank.android.apps.axess\|com.akbank.android.apps.axess:pushservice
  com.akbank.android.apps.axess\|com.akbank.android.apps.axess:remote
  com.akode.tosla\|com.akode.tosla
  com.akode.tosla\|com.akode.tosla:playcore_missing_splits_activity
  com.aktifbank.nkolay\|com.aktifbank.nkolay
  com.aktifbank.nkolay\|com.aktifbank.nkolay:playcore_missing_splits_activity
  com.android.adservices.api\|com.android.adservices.api
  com.android.apps.tag\|com.android.apps.tag
  com.android.backupconfirm\|com.android.backupconfirm
  com.android.bips\|com.android.bips
  com.android.bluetooth\|com.android.bluetooth
  com.android.bluetooth.overlay\|com.android.bluetooth.overlay
  com.android.bluetoothmidiservice\|com.android.bluetoothmidiservice
  com.android.browser\|com.android.browser
  com.android.browser\|com.android.browser:customtabs
  com.android.browser\|com.android.browser:fullsearch
  com.android.browser\|com.android.browser:media
  com.android.browser\|com.android.browser:megapp
  com.android.browser\|com.android.browser:phoenix
  com.android.browser\|com.android.browser:pushservice
  com.android.browser\|com.android.browser:webapps
  com.android.browser\|com.android.browser:widgetProvider
  com.android.calendar\|com.android.calendar
  com.android.calendar\|com.android.calendar:widgetProvider
  com.android.calllogbackup\|com.android.calllogbackup
  com.android.camera\|com.android.camera
  com.android.camera\|com.android.camera:remote
  com.android.camera\|com.android.camera:widgetProvider
  com.android.camera.overlay\|com.android.camera.overlay
  com.android.cameraextensions\|com.android.cameraextensions
  com.android.captiveportallogin\|com.android.captiveportallogin
  com.android.carrierconfig\|com.android.carrierconfig
  com.android.carrierconfig.overlay.common\|com.android.carrierconfig.overlay.common
  com.android.carrierconfig.overlay.miui\|com.android.carrierconfig.overlay.miui
  com.android.carrierdefaultapp\|com.android.carrierdefaultapp
  com.android.cellbroadcastreceiver\|com.android.cellbroadcastreceiver
  com.android.cellbroadcastreceiver.overlay.common\|com.android.cellbroadcastreceiver.overlay.common
  com.android.cellbroadcastservice\|com.android.cellbroadcastservice
  com.android.certinstaller\|com.android.certinstaller
  com.android.chrome\|com.android.chrome
  com.android.chrome\|com.android.chrome:browser_restart_process
  com.android.chrome\|com.android.chrome:launch_failed
  com.android.chrome\|com.android.chrome:playcore_missing_splits_activity
  com.android.chrome\|com.android.chrome:privileged_process0
  com.android.chrome\|com.android.chrome:privileged_process1
  com.android.chrome\|com.android.chrome:privileged_process2
  com.android.chrome\|com.android.chrome:privileged_process3
  com.android.chrome\|com.android.chrome:privileged_process4
  com.android.chrome\|com.android.chrome_zygote
  com.android.companiondevicemanager\|com.android.companiondevicemanager
  com.android.connectivity.resources\|com.android.connectivity.resources
  com.android.contacts\|com.android.contacts
  com.android.credentialmanager\|com.android.credentialmanager
  com.android.cts.ctsshim\|com.android.cts.ctsshim
  com.android.cts.priv.ctsshim\|com.android.cts.priv.ctsshim
  com.android.deskclock\|com.android.deskclock
  com.android.deskclock\|com.android.deskclock:remote
  com.android.devicelockcontroller\|com.android.devicelockcontroller
  com.android.dreams.basic\|com.android.dreams.basic
  com.android.dynsystem\|com.android.dynsystem
  com.android.email\|com.android.email
  com.android.emergency\|com.android.emergency
  com.android.externalstorage\|com.android.externalstorage
  com.android.federatedcompute.services\|com.android.federatedcompute.services
  com.android.fileexplorer\|com.android.fileexplorer
  com.android.fileexplorer\|com.android.fileexplorer:miuiplus
  com.android.fileexplorer\|com.android.fileexplorer:widgetProvider
  com.android.health.connect.backuprestore\|com.android.health.connect.backuprestore
  com.android.healthconnect.controller\|com.android.healthconnect.controller
  com.android.hotspot2.osulogin\|com.android.hotspot2.osulogin
  com.android.htmlviewer\|com.android.htmlviewer
  com.android.incallui\|com.android.incallui
  com.android.inputdevices\|com.android.inputdevices
  com.android.inputsettings.overlay.miui\|com.android.inputsettings.overlay.miui
  com.android.intentresolver\|com.android.intentresolver
  com.android.internal.display.cutout.emulation.corner\|com.android.internal.display.cutout.emulation.corner
  com.android.internal.display.cutout.emulation.double\|com.android.internal.display.cutout.emulation.double
  com.android.internal.display.cutout.emulation.hole\|com.android.internal.display.cutout.emulation.hole
  com.android.internal.display.cutout.emulation.tall\|com.android.internal.display.cutout.emulation.tall
  com.android.internal.display.cutout.emulation.waterfall\|com.android.internal.display.cutout.emulation.waterfall
  com.android.internal.systemui.navbar.gestural\|com.android.internal.systemui.navbar.gestural
  com.android.internal.systemui.navbar.gestural_extra_wide_back\|com.android.internal.systemui.navbar.gestural_extra_wide_back
  com.android.internal.systemui.navbar.gestural_narrow_back\|com.android.internal.systemui.navbar.gestural_narrow_back
  com.android.internal.systemui.navbar.gestural_wide_back\|com.android.internal.systemui.navbar.gestural_wide_back
  com.android.internal.systemui.navbar.threebutton\|com.android.internal.systemui.navbar.threebutton
  com.android.internal.systemui.navbar.transparent\|com.android.internal.systemui.navbar.transparent
  com.android.keychain\|com.android.keychain
  com.android.localtransport\|com.android.localtransport
  com.android.location.fused\|com.android.location.fused
  com.android.managedprovisioning\|com.android.managedprovisioning
  com.android.managedprovisioning\|com.android.managedprovisioning:webview
  com.android.managedprovisioning.overlay\|com.android.managedprovisioning.overlay
  com.android.mms\|com.android.mms
  com.android.mms\|com.android.mms:CMCCSsoService
  com.android.mms\|com.android.mms:appcustom
  com.android.mms\|com.android.mms:mms_service
  com.android.mms.service\|com.android.mms.service
  com.android.modulemetadata\|com.android.modulemetadata
  com.android.mtp\|com.android.mtp
  com.android.musicfx\|com.android.musicfx
  com.android.nearby.halfsheet\|com.android.nearby.halfsheet
  com.android.networkstack\|com.android.networkstack
  com.android.networkstack.overlay.miui\|com.android.networkstack.overlay.miui
  com.android.networkstack.tethering\|com.android.networkstack.tethering
  com.android.nfc\|com.android.nfc
  com.android.nfc\|com.android.nfc:beam
  com.android.nfc\|com.android.nfc:com.android.nfc.chooser
  com.android.ondevicepersonalization.services\|com.android.ondevicepersonalization.services
  com.android.ons\|com.android.ons
  com.android.ons\|com.android.phone
  com.android.overlay.cngmstelecomm\|com.android.overlay.cngmstelecomm
  com.android.overlay.gmscontactprovider\|com.android.overlay.gmscontactprovider
  com.android.overlay.gmssettingprovider\|com.android.overlay.gmssettingprovider
  com.android.overlay.gmssettings\|com.android.overlay.gmssettings
  com.android.overlay.gmstelecomm\|com.android.overlay.gmstelecomm
  com.android.overlay.gmstelephony\|com.android.overlay.gmstelephony
  com.android.overlay.systemui\|com.android.overlay.systemui
  com.android.pacprocessor\|com.android.pacprocessor
  com.android.permissioncontroller\|com.android.permissioncontroller
  com.android.phone\|com.android.phone
  com.android.phone.common.overlay.miui\|com.android.phone.common.overlay.miui
  com.android.phone.overlay.common\|com.android.phone.overlay.common
  com.android.phone.overlay.miui\|com.android.phone.overlay.miui
  com.android.printspooler\|com.android.printspooler
  com.android.providers.calendar\|com.android.providers.calendar
  com.android.providers.contacts\|com.android.providers.contacts
  com.android.providers.downloads\|com.android.providers.downloads
  com.android.providers.media\|android.process.media
  com.android.providers.media\|com.android.providers.media
  com.android.providers.media.module\|com.android.providers.media.module
  com.android.providers.media.module\|com.android.providers.media.module:PhotoPicker
  com.android.providers.partnerbookmarks\|com.android.providers.partnerbookmarks
  com.android.providers.settings\|com.android.providers.settings
  com.android.providers.settings.overlay\|com.android.providers.settings.overlay
  com.android.providers.telephony\|com.android.providers.telephony
  com.android.providers.telephony.overlay.miui\|com.android.providers.telephony.overlay.miui
  com.android.providers.userdictionary\|com.android.providers.userdictionary
  com.android.provision\|com.android.provision
  com.android.provision.resource.overlay\|com.android.provision.resource.overlay
  com.android.proxyhandler\|com.android.proxyhandler
  com.android.quicksearchbox\|com.android.quicksearchbox
  com.android.quicksearchbox\|com.android.quicksearchbox:ApplicationsProvider
  com.android.quicksearchbox\|com.android.quicksearchbox:pushservice
  com.android.quicksearchbox\|com.android.quicksearchbox:widgetProvider
  com.android.rkpdapp\|com.android.rkpdapp
  com.android.role.notes.enabled\|com.android.role.notes.enabled
  com.android.safetycenter.resources\|com.android.safetycenter.resources
  com.android.se\|com.android.se
  com.android.se.overlay.target\|com.android.se.overlay.target
  com.android.server.telecom\|com.android.server.telecom
  com.android.server.telecom.overlay.common\|com.android.server.telecom.overlay.common
  com.android.server.telecom.overlay.miui\|com.android.server.telecom.overlay.miui
  com.android.settings\|com.android.phone
  com.android.settings\|com.android.settings
  com.android.settings\|com.android.settings:pushservice
  com.android.settings\|com.android.settings:remote
  com.android.settings\|com.miui.backup
  com.android.settings.intelligence\|com.android.settings.intelligence
  com.android.settings.overlay.common\|com.android.settings.overlay.common
  com.android.settings.overlay.miui\|com.android.settings.overlay.miui
  com.android.settings.resource.overlay\|com.android.settings.resource.overlay
  com.android.sharedstoragebackup\|com.android.sharedstoragebackup
  com.android.shell\|com.android.shell
  com.android.simappdialog\|com.android.simappdialog
  com.android.smspush\|com.android.smspush
  com.android.soundrecorder\|com.android.soundrecorder
  com.android.soundrecorder\|com.android.soundrecorder:remote
  com.android.soundrecorder\|com.android.soundrecorder:sync
  com.android.statementservice\|com.android.statementservice
  com.android.stk\|com.android.stk
  com.android.stk.overlay.miui\|com.android.stk.overlay.miui
  com.android.storagemanager\|com.android.storagemanager
  com.android.systemui\|com.android.systemui
  com.android.systemui\|com.android.systemui:appclips.screenshot
  com.android.systemui\|com.android.systemui:fgservices
  com.android.systemui\|com.android.systemui:screenshot
  com.android.systemui\|com.android.systemui:sweetsweetdesserts
  com.android.systemui\|com.android.systemui:tuner
  com.android.systemui.accessibility.accessibilitymenu\|com.android.systemui.accessibility.accessibilitymenu
  com.android.systemui.gesture.line.overlay\|com.android.systemui.gesture.line.overlay
  com.android.systemui.navigation.bar.overlay\|com.android.systemui.navigation.bar.overlay
  com.android.systemui.overlay.common\|com.android.systemui.overlay.common
  com.android.systemui.overlay.miui\|com.android.systemui.overlay.miui
  com.android.theme.font.notoserifsource\|com.android.theme.font.notoserifsource
  com.android.thememanager\|com.android.thememanager
  com.android.thememanager\|com.android.thememanager:mamldataprovider
  com.android.thememanager\|com.android.thememanager:pushservice
  com.android.thememanager\|com.android.thememanager:videowallpaper
  com.android.thememanager.customthemeconfig.config.overlay\|com.android.thememanager.customthemeconfig.config.overlay
  com.android.traceur\|com.android.traceur
  com.android.updater\|com.android.updater
  com.android.uwb.resources\|com.android.uwb.resources
  com.android.vending\|com.android.vending
  com.android.virtualmachine.res\|com.android.virtualmachine.res
  com.android.vpndialogs\|com.android.vpndialogs
  com.android.wallpaper.livepicker\|com.android.wallpaper.livepicker
  com.android.wallpaperbackup\|com.android.wallpaperbackup
  com.android.wallpapercropper\|com.android.wallpapercropper
  com.android.wifi.dialog\|com.android.wifi.dialog
  com.android.wifi.resources\|com.android.wifi.resources
  com.android.wifi.resources.overlay.common\|com.android.wifi.resources.overlay.common
  com.android.wifi.resources.overlay.kalama\|com.android.wifi.resources.overlay.kalama
  com.android.wifi.resources.overlay.target\|com.android.wifi.resources.overlay.target
  com.android.wifi.resources.xiaomi\|com.android.wifi.resources.xiaomi
  com.app.sipay\|com.app.sipay
  com.app.sipay\|com.app.sipay:playcore_missing_splits_activity
  com.ataexpress.tiklagelsin\|com.ataexpress.tiklagelsin
  com.ataexpress.tiklagelsin\|com.ataexpress.tiklagelsin:alarmReceiverService
  com.ataexpress.tiklagelsin\|com.ataexpress.tiklagelsin:container
  com.ataexpress.tiklagelsin\|com.ataexpress.tiklagelsin:miqforegroundService
  com.ataexpress.tiklagelsin\|com.ataexpress.tiklagelsin:playcore_missing_splits_activity
  com.ataexpress.tiklagelsin\|com.ataexpress.tiklagelsin:pushservice
  com.ataexpress.tiklagelsin\|com.ataexpress.tiklagelsin:scannerService
  com.ataexpress.tiklagelsin\|com.ataexpress.tiklagelsin:transmitterService
  com.barn.promomatik.cekkazan\|com.barn.promomatik.cekkazan
  com.barn.promomatik.cekkazan\|com.barn.promomatik.cekkazan:playcore_missing_splits_activity
  com.biletdukkani.b2c\|com.biletdukkani.b2c
  com.binance.dev\|com.binance.dev
  com.binance.dev\|com.binance.dev:filedownloader
  com.binance.dev\|com.binance.dev:heap_analysis
  com.binance.dev\|com.binance.dev:nezha0
  com.binance.dev\|com.binance.dev:nezha1
  com.binance.dev\|com.binance.dev:nezha2
  com.binance.dev\|com.binance.dev:nezha3
  com.binance.dev\|com.binance.dev:nezha4
  com.binance.dev\|com.binance.dev:nezha5
  com.binance.dev\|com.binance.dev:onfido_process
  com.binance.dev\|com.binance.dev:playcore_missing_splits_activity
  com.binance.dev\|com.binance.dev:push
  com.bsp.catchlog\|com.bsp.catchlog
  com.cloud.tr\|com.cloud.tr
  com.cloud.tr\|com.cloud.tr:playcore_missing_splits_activity
  com.cloud.tr\|com.cloud.tr:push
  com.cloud.tr\|com.cloud.tr:pushservice
  com.cocacola.dahadaha\|com.cocacola.dahadaha
  com.cocacola.dahadaha\|com.cocacola.dahadaha:remote
  com.colendi.money_pay\|com.colendi.money_pay
  com.comuto\|com.comuto
  com.comuto\|com.comuto:Metrica
  com.comuto\|com.comuto:onfido_process
  com.comuto\|com.comuto:phoenix
  com.disney.disneyplus\|com.disney.disneyplus
  com.disney.disneyplus\|com.disney.disneyplus:playcore_missing_splits_activity
  com.duokan.phone.remotecontroller\|com.duokan.phone.remotecontroller
  com.duokan.phone.remotecontroller\|com.duokan.phone.remotecontroller:newinst
  com.excelliance.multiaccounts\|com.excelliance.multiaccounts
  com.fido.asm\|com.fido.asm
  com.finansbank.mobile.cepsube\|com.finansbank.mobile.cepsube
  com.flo.ayakkabi\|com.flo.ayakkabi
  com.flo.ayakkabi\|com.flo.ayakkabi:playcore_missing_splits_activity
  com.garanti.bonusapp\|com.garanti.bonusapp
  com.garanti.bonusapp\|com.garanti.bonusapp:pushservice
  com.garanti.cepsubesi\|com.garanti.cepsubesi
  com.garanti.cepsubesi\|com.garanti.cepsubesi:container
  com.garanti.cepsubesi\|com.garanti.cepsubesi:playcore_missing_splits_activity
  com.garanti.cepsubesi\|com.garanti.cepsubesi:pushservice
  com.goodix.fingerprint.setting\|com.goodix.fingerprint.setting
  com.google.android.accessibility.switchaccess\|com.google.android.accessibility.switchaccess
  com.google.android.accessibility.switchaccess\|com.google.android.accessibility.switchaccess:playcore_missing_splits_activity
  com.google.android.accessibility.switchaccess\|com.google.android.accessibility.switchaccess:primes_lifeboat
  com.google.android.apps.bard\|com.google.android.apps.bard
  com.google.android.apps.bard\|com.google.android.apps.bard:primes_lifeboat
  com.google.android.cellbroadcastreceiver.overlay.miui\|com.google.android.cellbroadcastreceiver.overlay.miui
  com.google.android.cellbroadcastservice.overlay.miui\|com.google.android.cellbroadcastservice.overlay.miui
  com.google.android.configupdater\|com.google.android.configupdater
  com.google.android.documentsui\|com.google.android.documentsui
  com.google.android.documentsui\|com.google.android.documentsui:com.android.documentsui.services
  com.google.android.ext.services\|com.google.android.ext.services
  com.google.android.ext.services\|com.google.android.ext.services:modelDownloaderServiceProcess
  com.google.android.ext.shared\|com.google.android.ext.shared
  com.google.android.gms\|com.google.android.gms
  com.google.android.gms.location.history\|com.google.android.gms.location.history
  com.google.android.gsf\|com.google.android.gsf
  com.google.android.gsf\|com.google.process.gapps
  com.google.android.gsf\|com.google.process.gservices
  com.google.android.inputmethod.latin\|com.google.android.inputmethod.latin
  com.google.android.marvin.talkback\|com.google.android.marvin.talkback
  com.google.android.marvin.talkback\|com.google.android.marvin.talkback:Tutorial
  com.google.android.marvin.talkback\|com.google.android.marvin.talkback:playcore_missing_splits_activity
  com.google.android.marvin.talkback\|com.google.android.marvin.talkback:primes_lifeboat
  com.google.android.onetimeinitializer\|com.google.android.onetimeinitializer
  com.google.android.overlay.gmsconfig\|com.google.android.overlay.gmsconfig
  com.google.android.overlay.modules.ext.services.cn\|com.google.android.overlay.modules.ext.services.cn
  com.google.android.printservice.recommendation\|com.google.android.printservice.recommendation
  com.google.android.webview\|com.google.android.webview
  com.google.android.wifi.resources.overlay.common\|com.google.android.wifi.resources.overlay.common
  com.goolge.android.wifi.resources.xiaomi\|com.goolge.android.wifi.resources.xiaomi
  com.haremaltin.android.haremaltin\|com.haremaltin.android.haremaltin
  com.haremaltin.android.haremaltin\|com.haremaltin.android.haremaltin:playcore_missing_splits_activity
  com.ictech.mono\|com.ictech.mono
  com.ictech.mono\|com.ictech.mono:pushservice
  com.inditex.ecommerce.bershka\|com.inditex.ecommerce.bershka
  com.ininal.wallet\|com.ininal.wallet
  com.ininal.wallet\|com.ininal.wallet:playcore_missing_splits_activity
  com.ininal.wallet\|com.ininal.wallet:pushservice
  com.inomera.sm\|com.inomera.sm
  com.inomera.sm\|com.inomera.sm:container
  com.inomera.sm\|com.inomera.sm:remote
  com.intertech.mobilemoneytransfer.activity\|com.intertech.mobilemoneytransfer.activity
  com.iyzico.assistant\|com.iyzico.assistant
  com.iyzico.assistant\|com.iyzico.assistant:pushservice
  com.kahvedunyasi.app\|com.kahvedunyasi.app
  com.kahvedunyasi.app\|com.kahvedunyasi.app:container
  com.kahvedunyasi.app\|com.kahvedunyasi.app:playcore_missing_splits_activity
  com.kahvedunyasi.app\|com.kahvedunyasi.app:pushservice
  com.kahvedunyasi.app\|com.kahvedunyasi.app:remote
  com.kuveytturk.mobil\|com.kuveytturk.mobil
  com.kuveytturk.mobil\|com.kuveytturk.mobil:p56bb93989f35954ba73cb6d3
  com.lbe.security.miui\|com.lbe.security.miui
  com.lbe.security.miui\|com.lbe.security.miui:ui
  com.mcdonalds.mobileapp\|com.mcdonalds.mobileapp
  com.mcdonalds.mobileapp\|com.mcdonalds.mobileapp:phoenix
  com.mfashiongallery.emag\|com.mfashiongallery.emag
  com.mfashiongallery.emag\|com.mfashiongallery.emag:gallery_wallpaper
  com.mfashiongallery.emag\|com.mfashiongallery.emag:pushservice
  com.milink.service\|com.milink.crossdeviceservice
  com.milink.service\|com.milink.runtime
  com.milink.service\|com.milink.service
  com.milink.service\|com.milink.service:audio
  com.milink.service\|com.milink.service:core
  com.milink.service\|com.milink.service:lelinkps
  com.milink.service\|com.milink.service:provider
  com.milink.service\|com.milink.service:ui
  com.milink.service\|com.xiaomi.vtcamera
  com.miui.accessibility\|com.miui.accessibility
  com.miui.accessibility\|com.miui.accessibility.common
  com.miui.accessibility\|com.miui.accessibility:remote
  com.miui.analytics\|com.miui.analytics
  com.miui.aod\|com.miui.aod
  com.miui.aod\|com.miui.aod:keyguardeditor
  com.miui.audiomonitor\|com.miui.audiomonitor
  com.miui.backup\|com.miui.backup
  com.miui.backup\|com.miui.backup:remote
  com.miui.bugreport\|com.miui.bugreport
  com.miui.bugreport\|com.miui.bugreport:pushservice
  com.miui.bugreport\|com.miui.bugreport:remote
  com.miui.carlink\|com.miui.carlink
  com.miui.cit\|com.android.phone
  com.miui.cit\|com.miui.cit
  com.miui.cloudbackup\|com.miui.cloudbackup
  com.miui.cloudservice\|com.miui.cloudservice
  com.miui.cloudservice\|com.miui.cloudservice:com.xiaomi.UPOService
  com.miui.cloudservice\|com.miui.cloudservice:dumplog
  com.miui.cloudservice\|com.miui.cloudservice:factory
  com.miui.cloudservice\|com.miui.cloudservice:galleryproxy
  com.miui.compass\|com.miui.compass
  com.miui.contentcatcher\|com.miui.contentcatcher
  com.miui.contentcatcher\|com.miui.contentcatcher:autofill
  com.miui.contentextension\|com.miui.contentextension
  com.miui.core\|com.miui.core
  com.miui.core\|com.miui.core:autoInstall
  com.miui.core.internal.services\|com.miui.core.internal.services
  com.miui.daemon\|com.miui.daemon
  com.miui.extraphoto\|com.miui.extraphoto
  com.miui.face.overlay.miui\|com.miui.face.overlay.miui
  com.miui.freeform\|com.miui.freeform
  com.miui.greenguard\|com.miui.greenguard
  com.miui.greenguard\|com.miui.greenguard:kid
  com.miui.greenguard\|com.miui.greenguard:pushservice
  com.miui.greenguard\|com.miui.greenguard:ui
  com.miui.guardprovider\|com.miui.guardprovider
  com.miui.home\|com.miui.home
  com.miui.hybrid\|com.miui.hybrid
  com.miui.hybrid\|com.miui.hybrid:Launcher0
  com.miui.hybrid\|com.miui.hybrid:Launcher1
  com.miui.hybrid\|com.miui.hybrid:Launcher2
  com.miui.hybrid\|com.miui.hybrid:Launcher3
  com.miui.hybrid\|com.miui.hybrid:Launcher4
  com.miui.hybrid\|com.miui.hybrid:float
  com.miui.hybrid\|com.miui.hybrid:pushservice
  com.miui.hybrid\|com.miui.hybrid:wakupui
  com.miui.hybrid\|com.miui.hybrid:worker
  com.miui.mediaviewer\|com.miui.mediaviewer
  com.miui.micloudsync\|com.miui.micloudsync
  com.miui.micloudsync\|com.miui.micloudsync:pushservice
  com.miui.miservice\|com.miui.miservice
  com.miui.mishare.connectivity\|com.miui.mishare.connectivity
  com.miui.mishare.connectivity\|com.miui.mishare.connectivity:ui
  com.miui.misightservice\|com.miui.misightservice
  com.miui.misound\|com.miui.misound
  com.miui.miwallpaper\|com.miui.miwallpaper
  com.miui.miwallpaper\|com.miui.miwallpaper:daemon
  com.miui.miwallpaper\|com.miui.miwallpaper:settings
  com.miui.miwallpaper.config.overlay\|com.miui.miwallpaper.config.overlay
  com.miui.miwallpaper.overlay.customize\|com.miui.miwallpaper.overlay.customize
  com.miui.nextpay\|com.miui.nextpay
  com.miui.nextpay\|com.miui.nextpay:pushservice
  com.miui.notification\|com.miui.notification
  com.miui.notification\|com.miui.notification:remote
  com.miui.otaprovision\|com.miui.otaprovision
  com.miui.otaprovision\|com.miui.otaprovision:pushservice
  com.miui.packageinstaller\|com.miui.packageinstaller
  com.miui.personalassistant\|com.miui.personalassistant
  com.miui.personalassistant\|com.miui.personalassistant:pushservice
  com.miui.phrase\|com.miui.phrase
  com.miui.powerkeeper\|all
  com.miui.powerkeeper\|com.miui.powerkeeper
  com.miui.powerkeeper\|ui
  com.miui.qr\|com.miui.qr
  com.miui.rom\|com.miui.rom
  com.miui.screenrecorder\|com.miui.screenrecorder
  com.miui.screenrecorder\|com.miui.screenrecorder:core
  com.miui.screenshot\|com.miui.screenshot
  com.miui.screenshot\|com.miui.screenshot:photo_editor
  com.miui.securityadd\|com.miui.securityadd
  com.miui.securityadd\|com.miui.securityadd.home
  com.miui.securityadd\|com.miui.securityadd:sdk
  com.miui.securitycenter\|com.miui.securitycenter
  com.miui.securitycenter\|com.miui.securitycenter.bootaware
  com.miui.securitycenter\|com.miui.securitycenter.remote
  com.miui.securitycenter\|com.miui.securitycenter:ui
  com.miui.securitycore\|com.miui.securitycore
  com.miui.securitycore\|com.miui.securitycore.remote
  com.miui.securitycore\|com.miui.securitycore:maintenance_mode
  com.miui.securitycore\|com.miui.securitycore:notification
  com.miui.securitycore\|com.miui.securitycore:provider
  com.miui.securitycore\|com.miui.securitycore:remote
  com.miui.securityinputmethod\|com.miui.securityinputmethod
  com.miui.settings.rro.device.config.overlay\|com.miui.settings.rro.device.config.overlay
  com.miui.settings.rro.device.hide.statusbar.overlay\|com.miui.settings.rro.device.hide.statusbar.overlay
  com.miui.settings.rro.device.type.overlay\|com.miui.settings.rro.device.type.overlay
  com.miui.system\|com.miui.system
  com.miui.system.overlay\|com.miui.system.overlay
  com.miui.systemAdSolution\|com.miui.systemAdSolution
  com.miui.systemAdSolution\|com.miui.systemAdSolution:pushservice
  com.miui.systemAdSolution\|com.miui.systemAdSolution:ui
  com.miui.systemui.carriers.overlay\|com.miui.systemui.carriers.overlay
  com.miui.systemui.devices.overlay\|com.miui.systemui.devices.overlay
  com.miui.systemui.overlay.devices.android\|com.miui.systemui.overlay.devices.android
  com.miui.thirdappassistant\|com.miui.thirdappassistant
  com.miui.thirdappassistant\|com.miui.thirdappassistant:persistent
  com.miui.thirdappassistant\|com.miui.thirdappassistant:pushservice
  com.miui.touchassistant\|com.miui.touchassistant
  com.miui.touchassistant\|com.miui.touchassistant:float
  com.miui.tsmclient\|com.miui.tsmclient
  com.miui.tsmclient\|com.miui.tsmclient:daemon
  com.miui.uireporter\|com.miui.uireporter
  com.miui.video\|com.miui.video
  com.miui.video\|com.miui.video:downloader
  com.miui.video\|com.miui.video:pushservice
  com.miui.video\|com.miui.video:widgetProvider
  com.miui.virtualsim\|com.miui.virtualsim
  com.miui.virtualsim\|com.miui.virtualsim:authentication
  com.miui.virtualsim\|com.miui.virtualsim:business
  com.miui.virtualsim\|com.miui.virtualsim:hybrid
  com.miui.virtualsim\|com.miui.virtualsim:pushservice
  com.miui.virtualsim\|com.miui.virtualsim:widgetProvider
  com.miui.voiceassist\|com.miui.voiceassist
  com.miui.voiceassist\|com.miui.voiceassist:core
  com.miui.voiceassist\|com.miui.voiceassist:download
  com.miui.voiceassist\|com.miui.voiceassist:filedownloader
  com.miui.voiceassist\|com.miui.voiceassist:inputMethodService
  com.miui.voiceassist\|com.miui.voiceassist:occupyScreen
  com.miui.voiceassist\|com.miui.voiceassist:provider
  com.miui.voiceassist\|com.miui.voiceassist:pushservice
  com.miui.voiceassist\|com.miui.voiceassist:remote
  com.miui.voiceassist\|com.miui.voiceassist:voice_trigger
  com.miui.voiceassist\|com.miui.voiceassist:widgetProvider
  com.miui.voiceassistoverlay\|com.miui.voiceassistoverlay
  com.miui.voicetrigger\|com.miui.voicetrigger
  com.miui.voicetrigger\|com.miui.voicetrigger:playcore_missing_splits_activity
  com.miui.voicetrigger\|com.miui.voicetrigger:pushservice
  com.miui.vpnsdkmanager\|com.miui.vpnsdkmanager
  com.miui.vsimcore\|com.android.phone
  com.miui.vsimcore\|com.miui.vsimcore
  com.miui.vsimcore\|com.miui.vsimcore:authentication
  com.miui.wallpaper.overlay.customize\|com.miui.wallpaper.overlay.customize
  com.miui.wmsvc\|com.miui.wmsvc
  com.miui.yellowpage\|com.miui.yellowpage
  com.miui.yellowpage\|com.miui.yellowpage:remoteWeb
  com.miuix.editor\|com.miuix.editor
  com.mobiletools.systemhelper\|com.mobiletools.systemhelper
  com.mobillium.papara\|com.mobillium.papara
  com.mobillium.papara\|com.mobillium.papara:pushservice
  com.mobisoft.beymen\|com.mobisoft.beymen
  com.mobisoft.beymen\|com.mobisoft.beymen:pushservice
  com.moneytolia.wallet\|com.moneytolia.wallet
  com.nestle.tr.nescafe.nescafe3in1loyaltyapp\|com.nestle.tr.nescafe.nescafe3in1loyaltyapp
  com.nestle.tr.nescafe.nescafe3in1loyaltyapp\|com.nestle.tr.nescafe.nescafe3in1loyaltyapp:remote
  com.nextcx.nays\|com.nextcx.nays
  com.nextcx.nays\|com.nextcx.nays:playcore_missing_splits_activity
  com.nextcx.nays\|com.nextcx.nays:pushservice
  com.nextcx.nays\|com.nextcx.nays:remote
  com.onbank.mobil\|com.onbank.mobil
  com.onbank.mobil\|com.onbank.mobil:gib
  com.onbank.mobil\|com.onbank.mobil:playcore_missing_splits_activity
  com.onbank.mobil\|com.onbank.mobil:pushservice
  com.openai.chatgpt\|com.openai.chatgpt
  com.papelmobile\|com.papelmobile
  com.paribu.app\|com.paribu.app
  com.paribu.app\|com.paribu.app:pushservice
  com.payoneer.android\|com.payoneer.android
  com.paypal.android.p2pmobile\|com.paypal.android.p2pmobile
  com.pepsico.kazandirio\|com.pepsico.kazandirio
  com.qti.dcf\|com.qti.dcf
  com.qti.dpmserviceapp\|com.qti.dpmserviceapp
  com.qti.phone\|com.qti.phone
  com.qti.qcc\|com.qti.qcc
  com.qti.qualcomm.datastatusnotification\|com.qti.qualcomm.datastatusnotification
  com.qti.qualcomm.deviceinfo\|com.qti.qualcomm.deviceinfo
  com.qti.service.colorservice\|com.qti.service.colorservice
  com.qualcomm.atfwd\|com.qualcomm.atfwd
  com.qualcomm.atfwd2\|com.qualcomm.atfwd2
  com.qualcomm.location\|com.qualcomm.location
  com.qualcomm.qcrilmsgtunnel\|com.qti.phone
  com.qualcomm.qcrilmsgtunnel\|com.qualcomm.qcrilmsgtunnel
  com.qualcomm.qti.biometrics.fingerprint.service\|com.qualcomm.qti.biometrics.fingerprint.service
  com.qualcomm.qti.biometrics.fingerprint.service\|com.qualcomm.qti.biometrics.fingerprint.service:remote
  com.qualcomm.qti.cne\|.qtidataservices
  com.qualcomm.qti.cne\|com.qualcomm.qti.cne
  com.qualcomm.qti.confdialer\|com.qualcomm.qti.confdialer
  com.qualcomm.qti.devicestatisticsservice\|com.qti.phone
  com.qualcomm.qti.devicestatisticsservice\|com.qualcomm.qti.devicestatisticsservice
  com.qualcomm.qti.dynamicddsservice\|com.qualcomm.qti.dynamicddsservice
  com.qualcomm.qti.gpudrivers.kalama.api33\|com.qualcomm.qti.gpudrivers.kalama.api33
  com.qualcomm.qti.lpa\|com.qualcomm.qti.lpa
  com.qualcomm.qti.performancemode\|com.qualcomm.qti.performancemode
  com.qualcomm.qti.poweroffalarm\|com.qualcomm.qti.poweroffalarm
  com.qualcomm.qti.powersavemode\|com.qualcomm.qti.powersavemode
  com.qualcomm.qti.qcolor\|com.qualcomm.qti.qcolor
  com.qualcomm.qti.qms.service.trustzoneaccess\|com.qualcomm.qti.qms.service.trustzoneaccess
  com.qualcomm.qti.remoteSimlockAuth\|com.qualcomm.qti.remoteSimlockAuth
  com.qualcomm.qti.ridemodeaudio\|com.qualcomm.qti.ridemodeaudio
  com.qualcomm.qti.server.qtiwifi\|com.qualcomm.qti.server.qtiwifi
  com.qualcomm.qti.services.systemhelper\|com.qualcomm.qti.services.systemhelper
  com.qualcomm.qti.simcontacts\|com.qualcomm.qti.simcontacts
  com.qualcomm.qti.telephonyservice\|com.qti.phone
  com.qualcomm.qti.telephonyservice\|com.qualcomm.qti.telephonyservice
  com.qualcomm.qti.trustedui\|com.qualcomm.qti.trustedui
  com.qualcomm.qti.uceShimService\|com.qualcomm.qti.uceShimService
  com.qualcomm.qti.uim\|com.qualcomm.qti.uim
  com.qualcomm.qti.uimGbaApp\|com.qualcomm.qti.uimGbaApp
  com.qualcomm.qti.workloadclassifier\|com.qualcomm.qti.workloadclassifier
  com.qualcomm.qti.xrcb\|com.qualcomm.qti.xrcb
  com.qualcomm.qti.xrvd.service\|com.qualcomm.qti.xrvd.service
  com.qualcomm.qtil.btdsda\|com.qualcomm.qtil.btdsda
  com.qualcomm.timeservice\|com.qualcomm.timeservice
  com.qualcomm.uimremoteclient\|com.qualcomm.uimremoteclient
  com.qualcomm.uimremoteserver\|com.qualcomm.uimremoteserver
  com.qualcomm.wfd.service\|com.qualcomm.wfd.service
  com.quicinc.voice.activation\|com.quicinc.voice.activation
  com.rectv.shot\|com.rectv.shot
  com.rectv.shot\|com.rectv.shot:Metrica
  com.restopos.crm_baydoner\|com.restopos.crm_baydoner
  com.reveny.nativecheck\|com.reveny.nativecheck
  com.rongcard.eid\|.eidservices
  com.rongcard.eid\|com.rongcard.eid
  com.sohu.inputmethod.sogou.xiaomi\|com.sohu.inputmethod.sogou.xiaomi
  com.sohu.inputmethod.sogou.xiaomi\|com.sohu.inputmethod.sogou.xiaomi:ac_checker
  com.sohu.inputmethod.sogou.xiaomi\|com.sohu.inputmethod.sogou.xiaomi:heap_analysis
  com.sohu.inputmethod.sogou.xiaomi\|com.sohu.inputmethod.sogou.xiaomi:p0
  com.sohu.inputmethod.sogou.xiaomi\|com.sohu.inputmethod.sogou.xiaomi:remote
  com.sohu.inputmethod.sogou.xiaomi\|com.sohu.inputmethod.sogou.xiaomi:scrashly
  com.sohu.inputmethod.sogou.xiaomi\|com.sohu.inputmethod.sogou.xiaomi:speech
  com.sohu.inputmethod.sogou.xiaomi\|com.sohu.inputmethod.status
  com.sohu.inputmethod.sogou.xiaomi\|sogou.mobile.explorer.hotwords
  com.solidict.gnc2\|com.solidict.gnc2
  com.spotify.music\|com.spotify.music
  com.spotify.music\|com.spotify.music:playcore_missing_splits_activity
  com.starbucks.tr\|com.starbucks.tr
  com.starbucks.tr\|com.starbucks.tr:alarmReceiverService
  com.starbucks.tr\|com.starbucks.tr:miqforegroundService
  com.starbucks.tr\|com.starbucks.tr:playcore_missing_splits_activity
  com.starbucks.tr\|com.starbucks.tr:scannerService
  com.starbucks.tr\|com.starbucks.tr:transmitterService
  com.supercell.brawlstars\|com.supercell.brawlstars
  com.tencent.mm\|com.tencent.mm
  com.tencent.mm\|com.tencent.mm:TMAssistantDownloadSDKService
  com.tencent.mm\|com.tencent.mm:appbrand0
  com.tencent.mm\|com.tencent.mm:appbrand1
  com.tencent.mm\|com.tencent.mm:appbrand2
  com.tencent.mm\|com.tencent.mm:appbrand3
  com.tencent.mm\|com.tencent.mm:appbrand4
  com.tencent.mm\|com.tencent.mm:backtrace__
  com.tencent.mm\|com.tencent.mm:cuploader
  com.tencent.mm\|com.tencent.mm:dexopt
  com.tencent.mm\|com.tencent.mm:exdevice
  com.tencent.mm\|com.tencent.mm:fallback
  com.tencent.mm\|com.tencent.mm:hotpot..
  com.tencent.mm\|com.tencent.mm:jectl
  com.tencent.mm\|com.tencent.mm:killprocesshelper
  com.tencent.mm\|com.tencent.mm:nospace
  com.tencent.mm\|com.tencent.mm:opengl_detector
  com.tencent.mm\|com.tencent.mm:patch
  com.tencent.mm\|com.tencent.mm:push
  com.tencent.mm\|com.tencent.mm:recovery
  com.tencent.mm\|com.tencent.mm:res_can_worker
  com.tencent.mm\|com.tencent.mm:sandbox
  com.tencent.mm\|com.tencent.mm:support
  com.tencent.mm\|com.tencent.mm:switch
  com.tencent.mm\|com.tencent.mm:tools
  com.tencent.mm\|com.tencent.mm:xweb_privileged_process_0
  com.tencent.mm\|com.tencent.mm:xweb_sandboxed_process_ex_0
  com.tencent.soter.soterserver\|com.tencent.soter.soterserver
  com.tmob.vodafonewallet.prod\|com.tmob.vodafonewallet.prod
  com.turkcell.ott\|com.turkcell.ott
  com.turkcell.ott\|com.turkcell.ott:container
  com.turkcell.ott\|com.turkcell.ott:playcore_missing_splits_activity
  com.turkcell.ott\|com.turkcell.ott:player
  com.turkcell.ott\|com.turkcell.ott:pushservice
  com.turkcell.paycell\|com.turkcell.paycell
  com.turkcell.paycell\|com.turkcell.paycell:playcore_missing_splits_activity
  com.turkcell.paycell\|com.turkcell.paycell:pushservice
  com.unilever.algida\|com.unilever.algida
  com.unilever.algida\|com.unilever.algida:pushservice
  com.unilever.algida\|com.unilever.algida:service
  com.unionpay.tsmservice.mi\|com.unionpay.tsmservice.mi
  com.upt.money.transfer.prod\|com.upt.money.transfer.prod
  com.upt.money.transfer.prod\|com.upt.money.transfer.prod:pushservice
  com.wallet.poca\|com.wallet.poca
  com.wallet.poca\|com.wallet.poca:container
  com.wallet.poca\|com.wallet.poca:phoenix
  com.wallet.poca\|com.wallet.poca:pushservice
  com.wapi.wapicertmanage\|com.wapi.wapicertmanage
  com.whatsapp\|com.whatsapp
  com.whatsapp\|com.whatsapp:account_switching
  com.xiaomi.ab\|com.xiaomi.ab
  com.xiaomi.account\|com.xiaomi.account
  com.xiaomi.account\|com.xiaomi.account:pushservice
  com.xiaomi.aiasst.service\|com.xiaomi.aiasst.service
  com.xiaomi.aiasst.vision\|com.xiaomi.aiasst.vision
  com.xiaomi.aiasst.vision\|com.xiaomi.aiasst.vision:widgetProvider
  com.xiaomi.aicr\|com.xiaomi.aicr
  com.xiaomi.aicr\|com.xiaomi.aicr:cognitionService
  com.xiaomi.aicr\|com.xiaomi.aicr:coreService
  com.xiaomi.aireco\|com.xiaomi.aireco
  com.xiaomi.aireco\|com.xiaomi.aireco:core
  com.xiaomi.aireco\|com.xiaomi.aireco:pushservice
  com.xiaomi.aireco\|com.xiaomi.aireco:widgetProvider
  com.xiaomi.aon\|com.xiaomi.aon
  com.xiaomi.barrage\|com.xiaomi.barrage
  com.xiaomi.bluetooth\|com.xiaomi.bluetooth
  com.xiaomi.bluetooth\|com.xiaomi.bluetooth:hello
  com.xiaomi.bluetooth\|com.xiaomi.bluetooth:pushservice
  com.xiaomi.bluetooth\|com.xiaomi.bluetooth:ui
  com.xiaomi.bluetooth.rro.device.config.overlay\|com.xiaomi.bluetooth.rro.device.config.overlay
  com.xiaomi.digitalkey\|com.xiaomi.digitalkey
  com.xiaomi.finddevice\|com.xiaomi.finddevice
  com.xiaomi.finddevice\|com.xiaomi.finddevice:capture
  com.xiaomi.finddevice\|com.xiaomi.finddevice:normal
  com.xiaomi.finddevice\|com.xiaomi.finddevice:pushservice
  com.xiaomi.finddevice\|com.xiaomi.finddevice:securitypush
  com.xiaomi.gamecenter.sdk.service\|com.xiaomi.gamecenter.sdk.service
  com.xiaomi.gamecenter.sdk.service\|com.xiaomi.gamecenter.sdk.service:heap_analysis
  com.xiaomi.gamecenter.sdk.service\|com.xiaomi.gamecenter.sdk.service:milink_ipc
  com.xiaomi.gamecenter.sdk.service\|com.xiaomi.gamecenter.sdk.service:pushservice
  com.xiaomi.gnss.polaris\|com.xiaomi.gnss.polaris
  com.xiaomi.joyose\|com.xiaomi.joyose
  com.xiaomi.joyose\|com.xiaomi.joyose:gunsight_service
  com.xiaomi.location.fused\|com.xiaomi.location.fused
  com.xiaomi.macro\|com.xiaomi.macro
  com.xiaomi.market\|com.xiaomi.market
  com.xiaomi.market\|com.xiaomi.market:guard
  com.xiaomi.market\|com.xiaomi.market:pushservice
  com.xiaomi.market\|com.xiaomi.market:widgetProvider
  com.xiaomi.metoknlp\|com.xiaomi.metoknlp
  com.xiaomi.mi_connect_service\|com.xiaomi.mi_connect_service
  com.xiaomi.mi_connect_service\|com.xiaomi.mi_connect_service:idm
  com.xiaomi.mi_connect_service\|com.xiaomi.mi_connect_service:pushservice
  com.xiaomi.micloud.sdk\|com.xiaomi.micloud.sdk
  com.xiaomi.migameservice\|com.xiaomi.migameservice
  com.xiaomi.mirror\|com.xiaomi.mirror
  com.xiaomi.mis\|com.xiaomi.mis
  com.xiaomi.misettings\|com.xiaomi.misettings
  com.xiaomi.misettings\|com.xiaomi.misettings:remote
  com.xiaomi.misettings\|com.xiaomi.misettings:widgetProvider
  com.xiaomi.mtb\|com.android.phone
  com.xiaomi.mtb\|com.xiaomi.mtb
  com.xiaomi.otrpbroker\|com.xiaomi.otrpbroker
  com.xiaomi.otrpbroker\|com.xiaomi.otrpbroker:remote
  com.xiaomi.payment\|com.xiaomi.payment
  com.xiaomi.payment\|com.xiaomi.payment:pushservice
  com.xiaomi.registration\|com.xiaomi.registration
  com.xiaomi.scanner\|com.xiaomi.scanner
  com.xiaomi.security.onetrack\|com.xiaomi.security.onetrack
  com.xiaomi.simactivate.service\|com.xiaomi.simactivate.service
  com.xiaomi.smarthome\|com.xiaomi.smarthome
  com.xiaomi.smarthome\|com.xiaomi.smarthome:acp
  com.xiaomi.smarthome\|com.xiaomi.smarthome:backtrace__
  com.xiaomi.smarthome\|com.xiaomi.smarthome:camera
  com.xiaomi.smarthome\|com.xiaomi.smarthome:core
  com.xiaomi.smarthome\|com.xiaomi.smarthome:frame1
  com.xiaomi.smarthome\|com.xiaomi.smarthome:frame2
  com.xiaomi.smarthome\|com.xiaomi.smarthome:heap_analysis
  com.xiaomi.smarthome\|com.xiaomi.smarthome:playcore_missing_splits_activity
  com.xiaomi.smarthome\|com.xiaomi.smarthome:player
  com.xiaomi.smarthome\|com.xiaomi.smarthome:plugin
  com.xiaomi.smarthome\|com.xiaomi.smarthome:plugin0
  com.xiaomi.smarthome\|com.xiaomi.smarthome:plugin1
  com.xiaomi.smarthome\|com.xiaomi.smarthome:plugin2
  com.xiaomi.smarthome\|com.xiaomi.smarthome:plugin3
  com.xiaomi.smarthome\|com.xiaomi.smarthome:plugin4
  com.xiaomi.smarthome\|com.xiaomi.smarthome:pushservice
  com.xiaomi.smarthome\|com.xiaomi.smarthome:widgetControl
  com.xiaomi.touchservice\|com.xiaomi.touchservice
  com.xiaomi.trustservice\|com.xiaomi.trustservice
  com.xiaomi.ugd\|com.xiaomi.ugd
  com.xiaomi.xaee\|com.xiaomi.xaee
  com.xiaomi.xmsf\|com.xiaomi.xmsf
  com.xiaomi.xmsf\|com.xiaomi.xmsf:kit7
  com.xiaomi.xmsf\|com.xiaomi.xmsf:passing
  com.xiaomi.xmsf\|com.xiaomi.xmsf:services
  com.xiaomi.xmsfkeeper\|com.xiaomi.xmsfkeeper
  com.ykb.android\|com.ykb.android:MAIN_PROCESS
  com.ykb.android\|com.ykb.android:container
  com.ykb.android\|com.ykb.android:playcore_missing_splits_activity
  com.ykb.android\|com.ykb.android:pushservice
  com.ykb.android\|com.ykb.android:remote
  com.ykb.avm\|com.ykb.avm
  com.ykb.avm\|com.ykb.avm:container
  com.ykb.avm\|com.ykb.avm:playcore_missing_splits_activity
  com.ykb.avm\|com.ykb.avm:pushservice
  com.zhenxi.hunter\|com.zhenxi.hunter
  com.zhenxi.hunter\|com.zhenxi.hunter_zygote
  com.zhiliaoapp.musically\|com.zhiliaoapp.musically
  com.zhiliaoapp.musically\|com.zhiliaoapp.musically:bm
  com.zhiliaoapp.musically\|com.zhiliaoapp.musically:downloader
  com.zhiliaoapp.musically\|com.zhiliaoapp.musically:playcore_missing_splits_activity
  com.zhiliaoapp.musically\|com.zhiliaoapp.musically:push
  com.zhiliaoapp.musically\|com.zhiliaoapp.musically:safemode
  com.zhiliaoapp.musically\|com.zhiliaoapp.musically:sandboxed_process1
  com.zhiliaoapp.musically\|com.zhiliaoapp.musically:sandboxed_process10
  com.zhiliaoapp.musically\|com.zhiliaoapp.musically:sandboxed_process2
  com.zhiliaoapp.musically\|com.zhiliaoapp.musically:sandboxed_process3
  com.zhiliaoapp.musically\|com.zhiliaoapp.musically:sandboxed_process4
  com.zhiliaoapp.musically\|com.zhiliaoapp.musically:sandboxed_process5
  com.zhiliaoapp.musically\|com.zhiliaoapp.musically:sandboxed_process6
  com.zhiliaoapp.musically\|com.zhiliaoapp.musically:sandboxed_process7
  com.zhiliaoapp.musically\|com.zhiliaoapp.musically:sandboxed_process8
  com.zhiliaoapp.musically\|com.zhiliaoapp.musically:sandboxed_process9
  com.zhiliaoapp.musically\|com.zhiliaoapp.musically:wallpaper
  com.zhiliaoapp.musically\|com.zhiliaoapp.musically:widgetProvider
  com.ziraat.ziraatmobil\|com.ziraat.ziraatmobil
  com.ziraat.ziraatmobil\|com.ziraat.ziraatmobil:container
  com.ziraat.ziraatmobil\|com.ziraat.ziraatmobil:playcore_missing_splits_activity
  com.ziraat.ziraatmobil\|com.ziraat.ziraatmobil:pushservice
  com.ziraat.ziraatmobil\|com.ziraat.ziraatmobil:remote
  finansbank.enpara\|finansbank.enpara
  io.github.vvb2060.keyattestation\|io.github.vvb2060.keyattestation
  io.github.vvb2060.mahoshojo\|io.github.vvb2060.mahoshojo
  io.github.vvb2060.mahoshojo\|io.github.vvb2060.mahoshojo_zygote
  isolated\|com.android.bips:com.android.bips.render.PdfRenderService
  isolated\|com.android.browser:sandboxed_process0:com.miui.org.chromium.content.app.SandboxedProcessService0
  isolated\|com.android.chrome:decoder_service:org.chromium.chrome.browser.photo_picker.DecoderService
  isolated\|com.android.chrome:sandboxed_process10:org.chromium.content.app.SandboxedProcessService10
  isolated\|com.android.chrome:sandboxed_process11:org.chromium.content.app.SandboxedProcessService11
  isolated\|com.android.chrome:sandboxed_process12:org.chromium.content.app.SandboxedProcessService12
  isolated\|com.android.chrome:sandboxed_process13:org.chromium.content.app.SandboxedProcessService13
  isolated\|com.android.chrome:sandboxed_process14:org.chromium.content.app.SandboxedProcessService14
  isolated\|com.android.chrome:sandboxed_process15:org.chromium.content.app.SandboxedProcessService15
  isolated\|com.android.chrome:sandboxed_process16:org.chromium.content.app.SandboxedProcessService16
  isolated\|com.android.chrome:sandboxed_process17:org.chromium.content.app.SandboxedProcessService17
  isolated\|com.android.chrome:sandboxed_process18:org.chromium.content.app.SandboxedProcessService18
  isolated\|com.android.chrome:sandboxed_process19:org.chromium.content.app.SandboxedProcessService19
  isolated\|com.android.chrome:sandboxed_process1:org.chromium.content.app.SandboxedProcessService1
  isolated\|com.android.chrome:sandboxed_process20:org.chromium.content.app.SandboxedProcessService20
  isolated\|com.android.chrome:sandboxed_process21:org.chromium.content.app.SandboxedProcessService21
  isolated\|com.android.chrome:sandboxed_process22:org.chromium.content.app.SandboxedProcessService22
  isolated\|com.android.chrome:sandboxed_process23:org.chromium.content.app.SandboxedProcessService23
  isolated\|com.android.chrome:sandboxed_process24:org.chromium.content.app.SandboxedProcessService24
  isolated\|com.android.chrome:sandboxed_process25:org.chromium.content.app.SandboxedProcessService25
  isolated\|com.android.chrome:sandboxed_process26:org.chromium.content.app.SandboxedProcessService26
  isolated\|com.android.chrome:sandboxed_process27:org.chromium.content.app.SandboxedProcessService27
  isolated\|com.android.chrome:sandboxed_process28:org.chromium.content.app.SandboxedProcessService28
  isolated\|com.android.chrome:sandboxed_process29:org.chromium.content.app.SandboxedProcessService29
  isolated\|com.android.chrome:sandboxed_process2:org.chromium.content.app.SandboxedProcessService2
  isolated\|com.android.chrome:sandboxed_process30:org.chromium.content.app.SandboxedProcessService30
  isolated\|com.android.chrome:sandboxed_process31:org.chromium.content.app.SandboxedProcessService31
  isolated\|com.android.chrome:sandboxed_process32:org.chromium.content.app.SandboxedProcessService32
  isolated\|com.android.chrome:sandboxed_process33:org.chromium.content.app.SandboxedProcessService33
  isolated\|com.android.chrome:sandboxed_process34:org.chromium.content.app.SandboxedProcessService34
  isolated\|com.android.chrome:sandboxed_process35:org.chromium.content.app.SandboxedProcessService35
  isolated\|com.android.chrome:sandboxed_process36:org.chromium.content.app.SandboxedProcessService36
  isolated\|com.android.chrome:sandboxed_process37:org.chromium.content.app.SandboxedProcessService37
  isolated\|com.android.chrome:sandboxed_process38:org.chromium.content.app.SandboxedProcessService38
  isolated\|com.android.chrome:sandboxed_process39:org.chromium.content.app.SandboxedProcessService39
  isolated\|com.android.chrome:sandboxed_process3:org.chromium.content.app.SandboxedProcessService3
  isolated\|com.android.chrome:sandboxed_process4:org.chromium.content.app.SandboxedProcessService4
  isolated\|com.android.chrome:sandboxed_process5:org.chromium.content.app.SandboxedProcessService5
  isolated\|com.android.chrome:sandboxed_process6:org.chromium.content.app.SandboxedProcessService6
  isolated\|com.android.chrome:sandboxed_process7:org.chromium.content.app.SandboxedProcessService7
  isolated\|com.android.chrome:sandboxed_process8:org.chromium.content.app.SandboxedProcessService8
  isolated\|com.android.chrome:sandboxed_process9:org.chromium.content.app.SandboxedProcessService9
  isolated\|com.android.ondevicepersonalization.services:com.android.ondevicepersonalization.libraries.plugin.internal.PluginExecutorService
  isolated\|com.android.printspooler:renderer:com.android.printspooler.renderer.PdfManipulationService
  isolated\|com.miui.hybrid:Sandbox0:org.hapjs.runtime.sandbox.SandboxService
  isolated\|com.miui.hybrid:Sandbox0:org.hapjs.runtime.sandbox.SandboxService$Sandbox0
  isolated\|com.miui.hybrid:Sandbox1:org.hapjs.runtime.sandbox.SandboxService
  isolated\|com.miui.hybrid:Sandbox1:org.hapjs.runtime.sandbox.SandboxService$Sandbox1
  isolated\|com.miui.hybrid:Sandbox2:org.hapjs.runtime.sandbox.SandboxService
  isolated\|com.miui.hybrid:Sandbox2:org.hapjs.runtime.sandbox.SandboxService$Sandbox2
  isolated\|com.miui.hybrid:Sandbox3:org.hapjs.runtime.sandbox.SandboxService
  isolated\|com.miui.hybrid:Sandbox3:org.hapjs.runtime.sandbox.SandboxService$Sandbox3
  isolated\|com.miui.hybrid:Sandbox4:org.hapjs.runtime.sandbox.SandboxService
  isolated\|com.miui.hybrid:Sandbox4:org.hapjs.runtime.sandbox.SandboxService$Sandbox4
  isolated\|com.miui.hybrid:sandboxed_process0:com.miui.org.chromium.content.app.SandboxedProcessService0
  isolated\|com.tencent.mm:xweb_sandboxed_process_0:com.tencent.xweb.pinus.sdk.process.SandboxedProcessService0
  isolated\|io.github.vvb2060.mahoshojo:io.github.vvb2060.mahoshojo.maho.MahoService2
  miui.systemui.plugin\|miui.systemui.plugin
  org.codeaurora.ims\|org.codeaurora.ims
  org.ifaa.aidl.manager\|org.ifaa.aidl.manager
  org.mipay.android.manager\|org.mipay.android.manager
  tr.com.cinemaximum\|tr.com.cinemaximum
  tr.com.hayatpay\|tr.com.hayatpay
  tr.com.kkb.android\|tr.com.kkb.android
  tr.com.param.android\|tr.com.param.android
  tr.com.param.android\|tr.com.param.android:container
  tr.com.param.android\|tr.com.param.android:pushservice
  vendor.qti.hardware.cacert.server\|vendor.qti.hardware.cacert.server
  vendor.qti.imsdatachannel\|vendor.qti.imsdatachannel
  vendor.qti.imsrcs\|vendor.qti.imsrcs
  vendor.qti.iwlan\|vendor.qti.iwlan
  vendor.qti.qesdk.sysservice\|vendor.qti.qesdk.sysservice
)




# Process each package and add to denylist
for entry in "${packages[@]}"; do
  package=$(echo $entry | cut -d'\|' -f1)
  proc=$(echo $entry | cut -d'\|' -f2)
  denylist_add "$package" "$proc"
done

# Temporarily stopped due to server need. This is torture for most people.

#if [ -f "/data/adb/tricky_store/keybox.xml" ]; then
#  rm "/data/adb/tricky_store/keybox.xml"
#fi
#random_keybox=$(find "/data/adb/modules/tricky_store/keyboxs/keyboxs/" -type f -name "*.xml" | shuf -n 1)
#if [ -z "$random_keybox" ]; then
#    exit 1
#fi
#cp "$random_keybox" "/data/adb/tricky_store/keybox.xml" 

#su -c killall com.google.android.gms
#su -c killall com.google.android.gms.unstable
